### ISSUE TITLE
test-sdist is run with BDist files

### ISSUE THREAD

**Issue by TiagodePAlves** [jupyterlab/maintainer-tools#113]
## Description

The [GH Action `test-sdist`](/jupyterlab/maintainer-tools/blob/v0.11.3/.github/actions/test-sdist/action.yml) currently install the SDist package ([line 30](/jupyterlab/maintainer-tools/blob/v0.11.3/.github/actions/test-sdist/action.yml#L30)) before testing. This installation step however generates a BDist (from the SDist) and installs that instead (you can see it happening in [this failed job](https://github.com/jupyter/nbconvert/runs/7702703892#step:3:520)).

## Problem

Testing a wheel is problematic because the project may remove test files from binaries, making the test step impossible. I found this issue when doing exactly that in jupyter/nbconvert#1822.

## Possible Solution

I'm not too versed in pip, but installing in `--editable`/`-e` mode does keep the source files intact, so it could be inserted directly in pip invocation ([line 30](/jupyterlab/maintainer-tools/blob/v0.11.3/.github/actions/test-sdist/action.yml#L30)). If forcing editable mode is not desired, only the default `package_spec` ([line 6](/jupyterlab/maintainer-tools/blob/v0.11.3/.github/actions/test-sdist/action.yml#L6)) could be modified.

**Comment by blink1073** [comment]
Sounds reasonable to change the default, but still allow non-editable mode if desired.   Would you like to submit a PR?

**Comment by TiagodePAlves** [comment]
Ok, I can do that. Should I add `--editable` to [`downstream-test`](/jupyterlab/maintainer-tools/blob/main/.github/actions/downstream-test/action.yml#L53) too?

**Comment by blink1073** [comment]
We had previously changed the default in downstream-test due to some errors we were seeing in various builds: https://github.com/jupyterlab/maintainer-tools/pull/70

**Comment by TiagodePAlves** [comment]
Alright, thanks!
