### ISSUE TITLE
Can we add `dependencies` to the allowed enforced labels?

### ISSUE THREAD

**Issue by wolfv** [jupyterlab/maintainer-tools#60]
It looks like depend-a-bot automatically adds the `dependencies` label when it bumps deps.

Could that be one of the allowed enforced labels?

https://github.com/jupyterlab/maintainer-tools/blob/c1125471fc0136d4fb27ebee419471e5ed8086a7/.github/actions/enforce-label/action.yml#L14

e.g. https://github.com/mamba-org/quetz/pull/484

**Comment by jtpio** [comment]
> e.g. https://github.com/mamba-org/quetz/pull/484

These can be labeled as `maintenance`.

**Comment by wolfv** [comment]
Yeah sure, I can label them with something else. But if dependabot already adds a decent label, wouldn't it be nice to just use it?

`dependencies` could internally be the same as `maintenance`.

So the idea is to raise this issue with `github-activity` then?

**Comment by wolfv** [comment]
Awesome!
